import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpenCheck, Clock, Gauge, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { BlockRenderer } from "@/components/blocks/block-renderer";
import { MaterialActions } from "@/components/material-actions";
import { MaterialCard } from "@/components/cards/material-card";
import { getDepartment, getMaterial, materials } from "@/data/mock-data";

export function generateStaticParams() { return materials.map((material) => ({ slug: material.slug })); }
export default async function MaterialPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const material = getMaterial(slug); if (!material) notFound(); const department = getDepartment(material.department)!; const related = materials.filter((item) => item.department === material.department && item.slug !== slug).slice(0, 2); return <main><section className="bg-[var(--surface)]"><div className="mx-auto w-full max-w-[1120px] px-4 py-10 sm:px-6 sm:py-14 lg:px-8"><Link href="/jelajahi" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted-foreground)] hover:text-[var(--primary)]"><ArrowLeft size={16} />Kembali ke jelajahi</Link><div className="mt-8 grid gap-10 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-center"><div><Badge style={{ backgroundColor: department.soft, color: department.color }}>{department.shortName} · {material.type}</Badge><h1 className="mt-5 max-w-3xl font-heading text-4xl font-bold leading-tight sm:text-[40px]">{material.title}</h1><div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-3 text-sm text-[var(--muted-foreground)]"><span className="flex items-center gap-2"><UserRound size={16} />{material.author}</span><span className="flex items-center gap-2"><Clock size={16} />{material.duration} menit</span><span className="flex items-center gap-2"><Gauge size={16} />{material.difficulty}</span></div><div className="mt-6"><MaterialActions slug={slug} /></div></div><img src={material.image} alt={`Pratinjau ${material.title}`} className="aspect-[4/3] w-full rounded-xl border border-[var(--border)] object-cover" /></div></div></section><section className="mx-auto w-full max-w-[1120px] px-4 py-12 sm:px-6 sm:py-14 lg:px-8"><article><div className="mb-10"><div className="flex items-center gap-2 text-[var(--primary)]"><BookOpenCheck size={20} /><h2 className="font-heading text-xl font-bold">Tujuan pembelajaran</h2></div><ul className="mt-4 grid gap-3 sm:grid-cols-2">{material.objectives.map((objective) => <li key={objective} className="flex gap-3 text-sm leading-6 text-[var(--muted-foreground)]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--primary)]" />{objective}</li>)}</ul></div><BlockRenderer blocks={material.blocks} /></article></section>{related.length > 0 && <section className="bg-[var(--surface)]"><div className="mx-auto w-full max-w-[1120px] px-4 section-space sm:px-6 lg:px-8"><p className="eyebrow">Lanjut belajar</p><h2 className="section-title mt-2">Materi terkait</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{related.map((item) => <MaterialCard key={item.slug} material={item} compact />)}</div></div></section>}</main>; }
