"use client";
import { useMemo, useState } from "react";
import { Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { SiteHeader } from "@/components/layout/site-header";
import { MaterialCard } from "@/components/cards/material-card";
import { Button } from "@/components/ui/button";
import { departments, materials } from "@/data/mock-data";

export default function ExplorePage() {
  const [search, setSearch] = useState(""); const [department, setDepartment] = useState("semua"); const [type, setType] = useState("semua"); const [difficulty, setDifficulty] = useState("semua"); const [duration, setDuration] = useState("semua"); const [sort, setSort] = useState("terbaru"); const [mobileFilters, setMobileFilters] = useState(false);
  const filtered = useMemo(() => materials.filter((m) => (!search || `${m.title} ${m.summary}`.toLowerCase().includes(search.toLowerCase())) && (department === "semua" || m.department === department) && (type === "semua" || m.type === type) && (difficulty === "semua" || m.difficulty === difficulty) && (duration === "semua" || (duration === "singkat" ? m.duration <= 20 : m.duration > 20))).sort((a, b) => sort === "populer" ? b.popularity - a.popularity : b.date.localeCompare(a.date)), [search, department, type, difficulty, duration, sort]);
  const reset = () => { setSearch(""); setDepartment("semua"); setType("semua"); setDifficulty("semua"); setDuration("semua"); };
  const filters = <><FilterGroup label="Program studi" value={department} onChange={setDepartment} items={[{ value: "semua", label: "Semua program" }, ...departments.map((d) => ({ value: d.slug, label: d.shortName }))]} /><FilterGroup label="Jenis media" value={type} onChange={setType} items={["semua", "Artikel", "Video", "Aktivitas", "Simulasi", "Kuis"].map((v) => ({ value: v, label: v === "semua" ? "Semua jenis" : v }))} /><FilterGroup label="Tingkat" value={difficulty} onChange={setDifficulty} items={["semua", "Dasar", "Menengah", "Lanjutan"].map((v) => ({ value: v, label: v === "semua" ? "Semua tingkat" : v }))} /><FilterGroup label="Durasi" value={duration} onChange={setDuration} items={[{ value: "semua", label: "Semua durasi" }, { value: "singkat", label: "≤ 20 menit" }, { value: "panjang", label: "> 20 menit" }]} /></>;
  return <><SiteHeader /><main className="container-app py-12 sm:py-16"><div className="max-w-2xl"><p className="eyebrow">Perpustakaan belajar</p><h1 className="mt-3 font-heading text-4xl font-bold tracking-[-.045em] sm:text-5xl">Jelajahi materi</h1><p className="mt-4 text-[#6a6b65]">Cari topik, pilih program studi, lalu temukan format belajar yang paling cocok untukmu.</p></div>
    <div className="mt-10 flex gap-6"><aside className="hidden w-64 shrink-0 lg:block"><div className="sticky top-24 rounded-2xl border border-[#e5e5df] bg-white p-5"><div className="mb-5 flex items-center justify-between"><p className="font-heading font-bold">Filter</p><button onClick={reset} className="text-xs font-semibold text-[#315c4c]">Reset</button></div><div className="grid gap-5">{filters}</div></div></aside>
      <div className="min-w-0 flex-1"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#8b8c86]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari materi atau topik…" className="h-12 w-full rounded-xl border border-[#dfe0da] bg-white pl-11 pr-4 text-sm outline-none focus:border-[#739382] focus:ring-2 focus:ring-[#739382]/10" /></label><Button variant="outline" className="h-12 lg:hidden" onClick={() => setMobileFilters(true)}><SlidersHorizontal size={17} /> Filter</Button><select value={sort} onChange={(e) => setSort(e.target.value)} className="h-12 rounded-xl border border-[#dfe0da] bg-white px-4 text-sm font-medium outline-none"><option value="terbaru">Terbaru</option><option value="populer">Terpopuler</option></select></div>
        <div className="my-6 flex items-center justify-between"><p className="text-sm text-[#74756f]"><strong className="text-[#262824]">{filtered.length}</strong> materi ditemukan</p><span className="hidden items-center gap-1 text-xs text-[#8a8b85] sm:flex"><Filter size={13} /> Gunakan filter untuk mempersempit hasil</span></div>
        {filtered.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((material) => <MaterialCard key={material.slug} material={material} />)}</div> : <div className="grid min-h-[360px] place-items-center rounded-2xl border border-dashed border-[#d8d9d3] bg-white text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#f0f2ee]"><Search className="text-[#6d7b72]" /></span><h2 className="mt-4 font-heading text-xl font-bold">Materi belum ditemukan</h2><p className="mt-2 text-sm text-[#777872]">Coba kata kunci atau filter yang berbeda.</p><Button onClick={reset} variant="outline" className="mt-5">Hapus filter</Button></div></div>}
      </div></div>
    {mobileFilters && <div className="fixed inset-0 z-[60] bg-black/25 lg:hidden" onClick={() => setMobileFilters(false)}><div className="absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto rounded-t-[24px] bg-white p-6" onClick={(e) => e.stopPropagation()}><div className="mb-6 flex items-center justify-between"><h2 className="font-heading text-xl font-bold">Filter materi</h2><Button variant="ghost" size="icon" onClick={() => setMobileFilters(false)}><X /></Button></div><div className="grid gap-5">{filters}</div><Button className="mt-7 w-full" onClick={() => setMobileFilters(false)}>Tampilkan {filtered.length} materi</Button></div></div>}
  </main><Footer /></>;
}

function FilterGroup({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: { value: string; label: string }[] }) { return <label className="grid gap-2 text-xs font-semibold text-[#4e504b]">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-xl border border-[#e1e1dc] bg-[#fbfbf9] px-3 text-sm font-normal outline-none focus:border-[#739382]">{items.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>; }
