import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2, Circle, Play } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { Footer } from "@/components/layout/footer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { departments, getDepartment, getMaterial, getProgram, programs } from "@/data/mock-data";

export function generateStaticParams() { return programs.map((program) => ({ slug: program.slug })); }
export default async function ProgramPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const program = getProgram(slug); if (!program) notFound(); const items = program.materialSlugs.map(getMaterial).filter(Boolean); return <><SiteHeader /><main><section className="relative overflow-hidden bg-[#253e34] text-white"><img src={program.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-15 mix-blend-luminosity" /><div className="container-app relative py-20 sm:py-24"><Badge className="bg-white/10 text-[#d6e8de]">Program kolaborasi</Badge><h1 className="mt-5 max-w-3xl font-heading text-4xl font-bold tracking-[-.05em] sm:text-6xl">{program.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/70">{program.description}</p><div className="mt-7 flex flex-wrap gap-2">{program.departments.map((slug) => { const dept = getDepartment(slug)!; return <Link key={slug} href={`/prodi/${slug}`} className="rounded-full border border-white/15 bg-white/[.07] px-3 py-1.5 text-xs font-semibold">{dept.shortName}</Link>; })}</div></div></section>
  <section className="container-app py-14"><div className="grid gap-10 lg:grid-cols-[1fr_330px]"><div><div className="mb-7 flex items-end justify-between"><div><p className="eyebrow">Alur belajar</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-.035em]">Materi dalam program</h2></div><p className="text-sm text-[#6d6f69]">{items.length} tahap</p></div><div className="grid gap-3">{items.map((material, index) => material && <Link href={`/materi/${material.slug}`} key={material.slug} className="group grid grid-cols-[auto_1fr_auto] items-center gap-4 rounded-2xl border border-[#e5e5df] bg-white p-4 transition hover:border-[#bacac1] hover:shadow-sm"><span className={`grid h-10 w-10 place-items-center rounded-full ${index === 0 ? "bg-[#315c4c] text-white" : "bg-[#f0f1ed] text-[#74766f]"}`}>{index === 0 ? <Play size={16} fill="currentColor" /> : index < program.progress / 33 ? <CheckCircle2 size={18} /> : <Circle size={18} />}</span><div><p className="text-xs font-semibold uppercase tracking-wider text-[#8a8b85]">Tahap {index + 1} · {material.type}</p><h3 className="mt-1 font-heading font-bold">{material.title}</h3><p className="mt-1 line-clamp-1 text-sm text-[#74756f]">{material.summary}</p></div><ArrowRight className="text-[#aaaca5] transition group-hover:translate-x-1 group-hover:text-[#315c4c]" /></Link>)}</div></div><aside><div className="sticky top-24 rounded-2xl border border-[#e5e5df] bg-white p-6"><p className="text-sm font-semibold">Progres belajarmu</p><div className="my-4 flex items-end justify-between"><span className="font-heading text-4xl font-bold tracking-[-.04em] text-[#315c4c]">{program.progress}%</span><span className="text-xs text-[#777]">tersimpan lokal</span></div><Progress value={program.progress} /><p className="mt-5 text-sm leading-6 text-[#6e706a]">Lanjutkan dari tahap terakhir. Progres disimpan di perangkat ini.</p><Button className="mt-5 w-full">Lanjutkan belajar <ArrowRight size={16} /></Button><div className="mt-6 border-t border-[#e8e8e3] pt-5"><p className="text-xs font-bold uppercase tracking-wider text-[#888a84]">Media pendukung</p><div className="mt-3 grid gap-2 text-sm"><span>• Worksheet refleksi</span><span>• Checklist praktik</span><span>• Referensi tambahan</span></div></div></div></aside></div></section>
  </main><Footer /></>; }

