"use client";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Plus, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { AdminBreadcrumb } from "@/components/admin/admin-breadcrumb";
import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { departments } from "@/data/mock-data";
export default function MaterialsAdminPage() { const [status, setStatus] = useState("semua"); const [department, setDepartment] = useState("semua"); const [sort, setSort] = useState("terbaru"); return <><AdminBreadcrumb items={[{ label: "Dashboard", href: "/admin" }, { label: "Materi" }]} /><AdminPageHeader title="Materi" description="Kelola materi, status publikasi, dan program studi dalam satu tempat." action={<Link href="/admin/materi/baru"><Button><Plus size={16} />Tambah materi</Button></Link>} /><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_180px_220px_170px]"><label className="relative"><span className="sr-only">Cari materi</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted-foreground)]" /><input className="control pl-10" placeholder="Cari judul materi" /></label><Select label="Filter status" value={status} onValueChange={setStatus} options={[{ value: "semua", label: "Semua status" }, { value: "terbit", label: "Terbit" }, { value: "draft", label: "Draft" }, { value: "jadwal", label: "Dijadwalkan" }]} /><Select label="Filter program studi" value={department} onValueChange={setDepartment} options={[{ value: "semua", label: "Semua program studi" }, ...departments.map((item) => ({ value: item.slug, label: item.shortName }))]} /><Select label="Urutkan materi" value={sort} onValueChange={setSort} options={[{ value: "terbaru", label: "Terbaru" }, { value: "terlama", label: "Terlama" }, { value: "judul", label: "Judul A–Z" }]} /></div><AdminDataTable /><div className="mt-5 flex flex-col items-center justify-between gap-3 sm:flex-row"><p className="text-sm text-[var(--muted-foreground)]">Menampilkan 1–6 dari 158 materi</p><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled><ChevronLeft size={15} />Sebelumnya</Button><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--primary)] text-sm font-semibold text-white">1</span><Button variant="outline" size="sm">Berikutnya <ChevronRight size={15} /></Button></div></div></>; }

