import Link from "next/link";
import { ArrowRight, BookOpenCheck, ChevronRight, Layers3, PlayCircle, Sparkles, UsersRound } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { DepartmentCard } from "@/components/cards/department-card";
import { MaterialCard } from "@/components/cards/material-card";
import { departments, gallery, materials, programs } from "@/data/mock-data";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="container-app relative overflow-hidden py-16 sm:py-24 lg:py-28"><div className="absolute right-[-12%] top-10 -z-10 h-[480px] w-[480px] rounded-full bg-[#edf4f0] blur-3xl" /><div className="grid items-center gap-14 lg:grid-cols-[1.1fr_.9fr]">
      <div><Badge className="mb-6 border border-[#d7e5dd] bg-[#f1f7f4] text-[#315c4c]"><Sparkles size={13} className="mr-1" /> Belajar lintas keahlian</Badge><h1 className="max-w-3xl font-heading text-[43px] font-bold leading-[1.07] tracking-[-0.055em] text-[#222420] sm:text-6xl">Satu ruang untuk belajar, berkarya, dan <span className="text-[#47715f]">tumbuh bersama.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#666862] sm:text-lg">Temukan materi dari enam program studi, pelajari keterampilan baru, dan lihat bagaimana setiap keahlian saling melengkapi.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/jelajahi"><Button size="lg" className="w-full sm:w-auto">Jelajahi materi <ArrowRight size={17} /></Button></Link><Link href="/program/persiapan-dunia-kerja"><Button size="lg" variant="outline" className="w-full sm:w-auto"><PlayCircle size={18} /> Lihat program</Button></Link></div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-sm text-[#696b65]"><span className="flex items-center gap-2"><BookOpenCheck size={17} className="text-[#47715f]" /> 158+ materi</span><span className="flex items-center gap-2"><UsersRound size={17} className="text-[#47715f]" /> 35 kontributor</span><span className="flex items-center gap-2"><Layers3 size={17} className="text-[#47715f]" /> 6 program studi</span></div></div>
      <div className="relative mx-auto w-full max-w-[480px]"><div className="rounded-[28px] border border-[#dfe4df] bg-white p-3 shadow-[0_30px_80px_rgba(41,56,47,.12)]"><img src={materials[0].image} alt="Siswa belajar pemrograman bersama" className="aspect-[4/3] w-full rounded-[20px] object-cover" /><div className="grid grid-cols-[1fr_auto] items-center gap-4 p-4"><div><p className="text-xs font-semibold text-[#47715f]">LANJUTKAN BELAJAR</p><p className="mt-1 font-heading font-bold">Algoritma Pertamaku</p></div><span className="grid h-11 w-11 place-items-center rounded-full bg-[#315c4c] text-white"><ChevronRight /></span></div></div><div className="absolute -left-4 top-8 hidden rounded-2xl border border-[#e2e4df] bg-white p-4 shadow-xl sm:block"><p className="text-2xl font-heading font-bold text-[#315c4c]">87%</p><p className="text-xs text-[#777]">siswa aktif</p></div></div>
    </div></section>
    <section className="border-y border-[#ecece7] bg-white py-20"><div className="container-app"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="eyebrow">Enam ruang keahlian</p><h2 className="section-title mt-3">Mulai dari yang kamu minati</h2></div><Link href="/jelajahi" className="hidden items-center gap-2 text-sm font-semibold text-[#315c4c] sm:flex">Lihat semua <ArrowRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{departments.map((department) => <DepartmentCard key={department.slug} department={department} />)}</div></div></section>
    <section className="container-app section-space"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow">Dipilih untukmu</p><h2 className="section-title mt-3">Materi pilihan minggu ini</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#71726c]">Belajar singkat, relevan, dan bisa langsung kamu praktikkan.</p></div><Link href="/jelajahi" className="hidden items-center gap-2 text-sm font-semibold text-[#315c4c] sm:flex">Semua materi <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{materials.filter((item) => item.featured).slice(0, 3).map((material) => <MaterialCard key={material.slug} material={material} />)}</div></section>
    <section className="bg-[#253e34] py-20 text-white"><div className="container-app"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b6d3c3]">Program kolaborasi</p><h2 className="mt-4 font-heading text-4xl font-bold leading-tight tracking-[-.04em]">Masalah nyata tidak mengenal batas program studi.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/65">Ikuti alur belajar yang menghubungkan pengetahuan, keterampilan, dan karakter dalam satu pengalaman.</p></div><div className="grid gap-3">{programs.map((program, index) => <Link href={`/program/${program.slug}`} key={program.slug} className="group flex items-center gap-5 rounded-2xl border border-white/10 bg-white/[.06] p-5 transition hover:bg-white/[.1]"><span className="font-heading text-2xl font-bold text-[#9bb7a7]">0{index + 1}</span><div className="flex-1"><h3 className="font-heading font-bold">{program.title}</h3><p className="mt-1 line-clamp-1 text-sm text-white/55">{program.description}</p></div><ArrowRight className="text-white/45 transition group-hover:translate-x-1 group-hover:text-white" /></Link>)}</div></div></div></section>
    <section className="container-app section-space"><div className="mb-10 text-center"><p className="eyebrow">Karya siswa</p><h2 className="section-title mt-3">Dari ruang belajar menjadi karya</h2></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0, 4).map((item, index) => <Link href="/galeri" key={item.id} className={`group relative overflow-hidden rounded-2xl ${index === 0 ? "col-span-2 row-span-2" : ""}`}><img src={item.image} alt={item.title} className="aspect-square h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-4 text-white"><p className="font-heading text-sm font-bold sm:text-base">{item.title}</p><p className="mt-1 text-xs text-white/70">{item.student}</p></div></Link>)}</div><div className="mt-8 text-center"><Link href="/galeri"><Button variant="outline">Lihat seluruh karya <ArrowRight size={16} /></Button></Link></div></section>
    <section className="container-app pb-8"><div className="rounded-[28px] bg-[#eef2ed] p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow">Tentang Ruang Sinergi</p><h2 className="mt-4 max-w-2xl font-heading text-3xl font-bold leading-tight tracking-[-.04em] sm:text-4xl">Pengetahuan menjadi lebih bermakna ketika dipelajari bersama.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#626962]">Ruang Sinergi membantu guru dan siswa SMK Negeri 1 Semarang berbagi media pembelajaran lintas program studi dalam format yang mudah dipahami dan nyaman digunakan.</p></div><Link href="/jelajahi"><Button>Mulai menjelajah <ArrowRight size={16} /></Button></Link></div></div></section>
  </main><Footer /></>;
}
