"use client";
import { useState } from "react";
import { DndContext, PointerSensor, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, verticalListSortingStrategy, useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { BarChart3, BookOpen, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, Copy, Eye, FileText, GalleryHorizontal, GripVertical, Image, Layers3, LayoutDashboard, Monitor, MoreHorizontal, Plus, Save, Settings2, Smartphone, Trash2 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useEditorStore, type EditorBlock } from "@/stores/editor-store";

const menu = [{ icon: LayoutDashboard, label: "Dashboard" }, { icon: FileText, label: "Materi", active: true }, { icon: BookOpen, label: "Program studi" }, { icon: Layers3, label: "Program kolaborasi" }, { icon: GalleryHorizontal, label: "Galeri" }, { icon: Image, label: "Media" }];
const steps = ["Informasi dasar", "Tujuan belajar", "Content blocks", "Publikasi", "Preview"];
export default function EditorPage() { const [step, setStep] = useState(2); const [mobilePreview, setMobilePreview] = useState(false); const { blocks, addBlock, setBlocks } = useEditorStore(); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const oldIndex = blocks.findIndex((b) => b.id === active.id); const newIndex = blocks.findIndex((b) => b.id === over.id); setBlocks(arrayMove(blocks, oldIndex, newIndex)); };
  return <div className="min-h-screen bg-[#f6f7f4]"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r border-[#e4e5df] bg-white p-4 lg:block"><Link href="/" className="flex items-center gap-2 px-2 py-2 font-heading font-bold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#315c4c] text-white"><BookOpen size={16} /></span> Ruang Sinergi</Link><div className="mt-8 grid gap-1">{menu.map(({ icon: Icon, label, active }) => <button key={label} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active ? "bg-[#edf3f0] text-[#315c4c]" : "text-[#666862] hover:bg-[#f5f5f1]"}`}><Icon size={18} />{label}</button>)}</div><div className="absolute inset-x-4 bottom-4 rounded-2xl bg-[#f2f3ef] p-4"><p className="text-xs font-semibold">Mode prototype</p><p className="mt-1 text-xs leading-5 text-[#777]">Perubahan disimpan sementara di perangkat ini.</p></div></aside>
    <div className="lg:pl-64"><header className="sticky top-0 z-10 border-b border-[#e4e5df] bg-white/90 backdrop-blur"><div className="flex h-16 items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Link href="/" className="lg:hidden"><ChevronLeft /></Link><div><p className="text-xs text-[#858680]">Materi / Baru</p><p className="font-heading text-sm font-bold">Membuat materi baru</p></div></div><div className="flex gap-2"><Button variant="outline" size="sm"><Eye size={15} /> <span className="hidden sm:inline">Preview</span></Button><Button size="sm"><Save size={15} /> Simpan draft</Button></div></div></header>
      <main className="mx-auto max-w-7xl p-4 sm:p-6"><div className="mb-6 overflow-x-auto rounded-2xl border border-[#e3e4de] bg-white p-3"><div className="flex min-w-[720px] items-center">{steps.map((label, index) => <button key={label} onClick={() => setStep(index)} className={`flex flex-1 items-center gap-2 rounded-xl px-3 py-2 text-left text-xs font-semibold ${step === index ? "bg-[#edf3f0] text-[#315c4c]" : index < step ? "text-[#315c4c]" : "text-[#858680]"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-[11px] ${index <= step ? "bg-[#315c4c] text-white" : "bg-[#ecece7]"}`}>{index + 1}</span>{label}</button>)}</div></div>
        {step === 2 ? <div className="grid gap-6 xl:grid-cols-[1fr_420px]"><section><div className="rounded-2xl border border-[#e3e4de] bg-white"><div className="flex items-center justify-between border-b border-[#e8e8e3] p-5"><div><h1 className="font-heading text-lg font-bold">Susun content blocks</h1><p className="mt-1 text-sm text-[#777872]">Seret untuk mengatur urutan materi.</p></div><Button onClick={addBlock}><Plus size={16} /> Tambah block</Button></div><div className="p-4"><DndContext sensors={sensors} onDragEnd={dragEnd}><SortableContext items={blocks.map((b) => b.id)} strategy={verticalListSortingStrategy}><div className="grid gap-3">{blocks.map((block, index) => <SortableBlock key={block.id} block={block} index={index} />)}</div></SortableContext></DndContext>{blocks.length === 0 && <div className="grid min-h-48 place-items-center rounded-xl border border-dashed text-sm text-[#777]">Belum ada block. Tambahkan block pertamamu.</div>}<Button variant="outline" className="mt-4 w-full border-dashed" onClick={addBlock}><Plus size={16} /> Tambah content block</Button></div></div></section>
          <aside><div className="sticky top-24 rounded-2xl border border-[#e3e4de] bg-white"><div className="flex items-center justify-between border-b border-[#e8e8e3] p-4"><div><p className="font-heading font-bold">Preview</p><p className="text-xs text-[#858680]">Diperbarui langsung</p></div><div className="flex rounded-lg bg-[#f0f1ed] p-1"><button onClick={() => setMobilePreview(false)} className={`rounded-md p-1.5 ${!mobilePreview ? "bg-white shadow-sm" : ""}`}><Monitor size={15} /></button><button onClick={() => setMobilePreview(true)} className={`rounded-md p-1.5 ${mobilePreview ? "bg-white shadow-sm" : ""}`}><Smartphone size={15} /></button></div></div><div className="bg-[#eef0eb] p-5"><div className={`mx-auto overflow-hidden rounded-xl border bg-white shadow-sm transition-all ${mobilePreview ? "max-w-[260px]" : "max-w-full"}`}><div className="aspect-[16/7] bg-[linear-gradient(135deg,#dbe9e1,#f3ede5)]" /><div className="p-4"><Badge>Informatika</Badge><h2 className="mt-3 font-heading text-xl font-bold">Judul materi barumu</h2><p className="mt-2 text-xs leading-5 text-[#777]">Ringkasan singkat materi akan tampil di bagian ini.</p><div className="mt-5 grid gap-2">{blocks.map((block) => <div key={block.id} className="rounded-lg border border-[#e8e8e3] p-3"><p className="text-[10px] font-bold uppercase text-[#8a8b85]">{block.type}</p><p className="mt-1 text-xs font-semibold">{block.title}</p></div>)}</div></div></div></div></div></aside></div> : <StepPlaceholder step={step} onNext={() => setStep(Math.min(step + 1, 4))} />}
        <div className="mt-6 flex justify-between"><Button variant="outline" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}><ChevronLeft size={16} /> Sebelumnya</Button><Button onClick={() => setStep(Math.min(4, step + 1))} disabled={step === 4}>Selanjutnya <ChevronRight size={16} /></Button></div>
      </main>
    </div></div>;
}

function SortableBlock({ block, index }: { block: EditorBlock; index: number }) { const { removeBlock, duplicateBlock, toggleBlock } = useEditorStore(); const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: block.id }); return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition }} className={`rounded-xl border border-[#e1e2dc] bg-[#fbfbf9] ${isDragging ? "z-20 shadow-xl" : ""}`}><div className="flex items-center gap-2 p-3"><button {...attributes} {...listeners} className="touch-none text-[#aaa]" aria-label="Seret block"><GripVertical size={18} /></button><span className="grid h-8 w-8 place-items-center rounded-lg bg-white text-xs font-bold text-[#777]">{index + 1}</span><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-[#898a84]">{block.type}</p><p className="truncate text-sm font-semibold">{block.title}</p></div><button onClick={() => toggleBlock(block.id)} className="rounded-lg p-2 hover:bg-white"><ChevronDown size={16} className={block.collapsed ? "-rotate-90" : ""} /></button><button onClick={() => duplicateBlock(block.id)} className="rounded-lg p-2 hover:bg-white"><Copy size={16} /></button><button onClick={() => removeBlock(block.id)} className="rounded-lg p-2 text-[#a35d52] hover:bg-[#f8ece9]"><Trash2 size={16} /></button></div>{!block.collapsed && <div className="grid gap-3 border-t border-[#e8e8e3] p-4 sm:grid-cols-[140px_1fr]"><label className="grid gap-1 text-xs font-semibold text-[#656762]">Jenis block<select className="h-10 rounded-lg border bg-white px-3 font-normal"><option>{block.type}</option><option>image</option><option>video</option><option>quiz</option></select></label><label className="grid gap-1 text-xs font-semibold text-[#656762]">Judul<input defaultValue={block.title} className="h-10 rounded-lg border bg-white px-3 font-normal outline-none focus:border-[#779685]" /></label></div>}</div>; }
function StepPlaceholder({ step, onNext }: { step: number; onNext: () => void }) { const content = [{ title: "Informasi dasar", icon: FileText, fields: ["Judul materi", "Ringkasan", "Program studi", "Jenis media"] }, { title: "Tujuan pembelajaran", icon: BarChart3, fields: ["Tujuan pertama", "Tujuan kedua", "Capaian pembelajaran"] }, { title: "", icon: MoreHorizontal, fields: [] }, { title: "Pengaturan publikasi", icon: Settings2, fields: ["Status publikasi", "Tanggal terbit", "Akses materi"] }, { title: "Preview materi", icon: Eye, fields: ["Periksa tampilan desktop", "Periksa tampilan seluler", "Siap dipublikasikan"] }][step]; const Icon = content.icon; return <div className="rounded-2xl border border-[#e3e4de] bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf3f0] text-[#315c4c]"><Icon /></span><div><p className="text-xs font-semibold text-[#858680]">Langkah {step + 1} dari 5</p><h1 className="font-heading text-xl font-bold">{content.title}</h1></div></div><div className="mt-8 grid gap-4">{content.fields.map((field, i) => <label key={field} className="grid gap-2 text-sm font-semibold">{field}{step === 4 ? <div className="flex items-center gap-3 rounded-xl border p-4 text-sm font-normal"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#315c4c] text-white">✓</span>{field}</div> : <input placeholder={i === 0 && step === 0 ? "Contoh: Dasar algoritma pemrograman" : `Isi ${field.toLowerCase()}…`} className="h-12 rounded-xl border border-[#dedfd9] px-4 font-normal outline-none focus:border-[#779685] focus:ring-2 focus:ring-[#779685]/10" />}</label>)}</div><Button className="mt-8" onClick={onNext}>Simpan & lanjutkan <ChevronRight size={16} /></Button></div>; }
