"use client";
import { useEffect, useState } from "react";
import { Images, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select } from "@/components/ui/select";
import { departments, gallery } from "@/data/mock-data";
import type { GalleryItem } from "@/types";

export default function GalleryPage() {
  const [department, setDepartment] = useState("semua"); const [type, setType] = useState("semua"); const [selected, setSelected] = useState<GalleryItem | null>(null);
  const items = gallery.filter((item) => (department === "semua" || item.department === department) && (type === "semua" || item.type === type));
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, []);
  return <main className="container-app py-12 sm:py-16"><div className="max-w-3xl"><p className="eyebrow">Galeri siswa</p><h1 className="mt-2 font-heading text-4xl font-bold sm:text-[40px]">Karya tumbuh dari proses belajar.</h1><p className="mt-4 max-w-2xl leading-7 text-[var(--muted-foreground)]">Lihat proyek, pertunjukan, karya digital, dan dokumentasi siswa dari berbagai program studi.</p></div><div className="mt-10 flex flex-col gap-3 border-y border-[var(--border)] py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-sm font-semibold"><Images size={18} />{items.length} karya</div><div className="grid gap-3 sm:grid-cols-2"><Select label="Filter program studi" value={department} onValueChange={setDepartment} options={[{ value: "semua", label: "Semua program studi" }, ...departments.map((item) => ({ value: item.slug, label: item.shortName }))]} /><Select label="Filter jenis karya" value={type} onValueChange={setType} options={[{ value: "semua", label: "Semua jenis karya" }, ...["Karya digital", "Pertunjukan", "Proyek", "Dokumentasi"].map((value) => ({ value, label: value }))]} /></div></div><div className="mt-8 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="group text-left"><img src={item.image} alt={item.title} className="aspect-[4/3] w-full rounded-2xl border border-[var(--border)] object-cover transition group-hover:-translate-y-0.5 group-hover:border-[#aebbb3]" /><div className="pt-4"><Badge>{item.type}</Badge><h2 className="mt-3 font-heading text-xl font-bold">{item.title}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{item.student} · {item.year}</p></div></button>)}</div>
    {selected && <div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-4" role="presentation" onClick={() => setSelected(null)}><div role="dialog" aria-modal="true" aria-labelledby="gallery-title" className="relative max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-[20px] border border-[var(--border)] bg-[var(--surface)]" onClick={(event) => event.stopPropagation()}><Button variant="secondary" size="icon" className="absolute right-4 top-4 z-10" onClick={() => setSelected(null)} aria-label="Tutup detail karya"><X size={18} /></Button><img src={selected.image} alt={selected.title} className="aspect-[16/9] w-full object-cover" /><div className="p-6 sm:p-8"><Badge>{selected.type}</Badge><h2 id="gallery-title" className="mt-3 font-heading text-2xl font-bold">{selected.title}</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{selected.student} · {selected.year}</p><p className="mt-5 leading-7 text-[var(--muted-foreground)]">{selected.description}</p></div></div></div>}
  </main>;
}
