import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BookOpen, ImageIcon, Users } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { SiteHeader } from "@/components/layout/site-header";
import { MaterialCard } from "@/components/cards/material-card";
import { Badge } from "@/components/ui/badge";
import { departments, gallery, getDepartment, materials, programs } from "@/data/mock-data";

export function generateStaticParams() { return departments.map((department) => ({ slug: department.slug })); }
export default async function DepartmentPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const department = getDepartment(slug); if (!department) notFound(); const items = materials.filter((m) => m.department === slug); const works = gallery.filter((g) => g.department === slug); const collabs = programs.filter((p) => p.departments.includes(slug)); return <><SiteHeader /><main>
  <section className="border-b border-[#e5e5df]" style={{ background: department.soft }}><div className="container-app py-16 sm:py-20"><Badge style={{ background: "rgba(255,255,255,.65)", color: department.color }}>Program Studi</Badge><div className="mt-5 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><h1 className="max-w-3xl font-heading text-4xl font-bold tracking-[-.045em] sm:text-6xl" style={{ color: department.color }}>{department.name}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#5f625d]">{department.description} Pelajari konsep melalui media interaktif, contoh nyata, dan aktivitas yang dirancang untuk siswa SMK.</p></div><div className="flex gap-3"><Stat icon={<BookOpen size={18} />} value={department.stats.materials} label="Materi" /><Stat icon={<Users size={18} />} value={department.stats.contributors} label="Kontributor" /></div></div></div></section>
  <section className="container-app section-space"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow" style={{ color: department.color }}>Baru diperbarui</p><h2 className="section-title mt-3">Materi terbaru</h2></div><Link href={`/jelajahi?prodi=${slug}`} className="hidden items-center gap-2 text-sm font-semibold sm:flex" style={{ color: department.color }}>Lihat semua <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.length ? items.slice(0, 3).map((material) => <MaterialCard key={material.slug} material={material} />) : materials.slice(0, 3).map((material) => <MaterialCard key={material.slug} material={material} />)}</div></section>
  <section className="border-y border-[#e6e6e0] bg-white py-20"><div className="container-app grid gap-12 lg:grid-cols-2"><div><p className="eyebrow" style={{ color: department.color }}>Media yang tersedia</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-.035em]">Belajar dengan berbagai format</h2><div className="mt-7 grid grid-cols-2 gap-3">{["Materi ringkas", "Video praktik", "Aktivitas mandiri", "Kuis interaktif"].map((label) => <div key={label} className="rounded-2xl border border-[#e5e5df] bg-[#fbfbf9] p-4 text-sm font-semibold"><span className="mb-3 grid h-9 w-9 place-items-center rounded-xl" style={{ background: department.soft, color: department.color }}><ImageIcon size={18} /></span>{label}</div>)}</div></div><div><p className="eyebrow" style={{ color: department.color }}>Kontributor</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-.035em]">Belajar dari praktisi sekolah</h2><div className="mt-7 grid gap-3">{Array.from(new Set(items.map((m) => m.author))).concat(["Tim Kurikulum SMKN 1 Semarang"]).slice(0, 3).map((name, i) => <div key={name} className="flex items-center gap-4 rounded-2xl border border-[#e5e5df] p-4"><span className="grid h-11 w-11 place-items-center rounded-full font-bold text-white" style={{ background: department.color }}>{name.split(" ").slice(-1)[0][0]}</span><div><p className="font-semibold">{name}</p><p className="text-xs text-[#777]">Guru & kontributor materi</p></div></div>)}</div></div></div></section>
  {works.length > 0 && <section className="container-app section-space"><p className="eyebrow" style={{ color: department.color }}>Galeri</p><h2 className="section-title mt-3">Karya dari siswa</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{works.map((work) => <Link href="/galeri" key={work.id} className="group overflow-hidden rounded-2xl border border-[#e5e5df] bg-white"><img src={work.image} alt={work.title} className="aspect-[16/8] w-full object-cover transition group-hover:scale-[1.02]" /><div className="p-5"><h3 className="font-heading font-bold">{work.title}</h3><p className="mt-1 text-sm text-[#777]">{work.student}</p></div></Link>)}</div></section>}
  {collabs.length > 0 && <section className="container-app pb-10"><div className="rounded-[24px] p-8" style={{ background: department.soft }}><p className="eyebrow" style={{ color: department.color }}>Lintas keahlian</p><h2 className="mt-3 font-heading text-2xl font-bold">Program kolaborasi terkait</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{collabs.map((program) => <Link href={`/program/${program.slug}`} key={program.slug} className="flex items-center justify-between rounded-xl bg-white p-4 font-semibold">{program.title}<ArrowRight size={17} /></Link>)}</div></div></section>}
  </main><Footer /></>; }

function Stat({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="min-w-24 rounded-2xl border border-white/60 bg-white/55 p-4 backdrop-blur"><span className="text-[#656861]">{icon}</span><p className="mt-3 font-heading text-2xl font-bold">{value}</p><p className="text-xs text-[#747771]">{label}</p></div>; }

