import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpenCheck, Clock, Gauge, UserRound } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { Footer } from "@/components/layout/footer";
import { Badge } from "@/components/ui/badge";
import { BlockRenderer } from "@/components/blocks/block-renderer";
import { MaterialActions } from "@/components/material-actions";
import { MaterialCard } from "@/components/cards/material-card";
import { getDepartment, getMaterial, materials } from "@/data/mock-data";

export function generateStaticParams() { return materials.map((material) => ({ slug: material.slug })); }
export default async function MaterialPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const material = getMaterial(slug); if (!material) notFound(); const department = getDepartment(material.department)!; const related = materials.filter((m) => m.department === material.department && m.slug !== slug).slice(0, 2); return <><SiteHeader /><main><section className="container-app py-10 sm:py-14"><Link href="/jelajahi" className="inline-flex items-center gap-2 text-sm font-semibold text-[#6d6f69] hover:text-[#315c4c]"><ArrowLeft size={16} /> Kembali ke jelajahi</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_380px] lg:items-start"><div><Badge style={{ background: department.soft, color: department.color }}>{department.shortName} · {material.type}</Badge><h1 className="mt-5 max-w-4xl font-heading text-4xl font-bold leading-[1.12] tracking-[-.045em] sm:text-5xl">{material.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-[#676963] sm:text-lg">{material.summary}</p><div className="mt-7 flex flex-wrap items-center gap-x-5 gap-y-3 text-sm text-[#686a64]"><span className="flex items-center gap-2"><UserRound size={16} /> {material.author}</span><span className="flex items-center gap-2"><Clock size={16} /> {material.duration} menit</span><span className="flex items-center gap-2"><Gauge size={16} /> {material.difficulty}</span></div><div className="mt-7"><MaterialActions slug={slug} /></div></div><img src={material.image} alt="" className="aspect-[4/3] w-full rounded-[24px] object-cover shadow-[0_20px_50px_rgba(35,43,38,.1)]" /></div></section>
  <section className="border-y border-[#e6e6e0] bg-white"><div className="container-app grid gap-10 py-12 lg:grid-cols-[1fr_320px]"><article className="max-w-3xl"><div className="mb-10 rounded-2xl border border-[#dce6e0] bg-[#f3f8f5] p-6"><div className="flex items-center gap-2 text-[#315c4c]"><BookOpenCheck size={20} /><h2 className="font-heading font-bold">Tujuan pembelajaran</h2></div><ul className="mt-4 grid gap-3">{material.objectives.map((objective) => <li key={objective} className="flex gap-3 text-sm leading-6 text-[#565d58]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#5e8672]" />{objective}</li>)}</ul></div><BlockRenderer blocks={material.blocks} /></article><aside className="hidden lg:block"><div className="sticky top-24 rounded-2xl border border-[#e5e5df] bg-[#fbfbf9] p-5"><p className="font-heading font-bold">Dalam materi ini</p><div className="mt-4 grid gap-3 text-sm text-[#686a64]"><span>1. Tujuan pembelajaran</span>{material.blocks.map((block, i) => <span key={block.id}>{i + 2}. {block.block_type.replace("-", " ")}</span>)}</div></div></aside></div></section>
  {related.length > 0 && <section className="container-app section-space"><p className="eyebrow">Lanjut belajar</p><h2 className="section-title mt-3">Materi terkait</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{related.map((item) => <MaterialCard key={item.slug} material={item} compact />)}</div></section>}
  </main><Footer /></>; }
